version: "3.9"

services:
  kafka:
    image: wurstmeister/kafka:2.13-2.7.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "KafkaTopicIN:1:1,KafkaTopicOUT:1:1"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"

  app:
    build:
      context: .
    depends_on:
      - kafka
      - mongo
    environment:
      KAFKA_HOST: kafka
      MONGO_HOST: mongo
      MONGO_DB: mydatabase
      MONGO_COLLECTION: mycollection
    command: python app.py


