version: '3'

services:

  kafka-window-consumer:
    image: python:3.9
    container_name: kafka-window-consumer
    working_dir: /app
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./:/app
    environment:
      PYTHONUNBUFFERED: 1
    command: python KafkaWindowConsumer.py

  kafka:
   image: confluentinc/cp-kafka:5.2.1
   hostname: kafka
   container_name: kafka
   ports:
     - "2181:2181"
     - "9092:9092"
   environment:
     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
     KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
     KAFKA_CREATE_TOPICS: "KafkaTopicIN:1,KafkaTopicOUT:1"
   depends_on:
     - zookeeper

  zookeeper:
   image: confluentinc/cp-zookeeper:5.2.1
   hostname: zookeeper
   ports:
     - "2181:2181"
   environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000

